//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleClassicTheme.Taskbar.ThemeEngine.Themes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Luna {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Luna() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleClassicThemeTaskbar.ThemeEngine.Themes.Luna", typeof(Luna).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StartButton {
            get {
                object obj = ResourceManager.GetObject("StartButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 98.
        /// </summary>
        internal static string StartButton_Width {
            get {
                return ResourceManager.GetString("StartButton.Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 71.
        /// </summary>
        internal static string SystemTray_BaseWidth {
            get {
                return ResourceManager.GetString("SystemTray.BaseWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11,7.
        /// </summary>
        internal static string SystemTray_FirstIconPosition {
            get {
                return ResourceManager.GetString("SystemTray.FirstIconPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SystemTrayBorder {
            get {
                object obj = ResourceManager.GetObject("SystemTrayBorder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SystemTrayTexture {
            get {
                object obj = ResourceManager.GetObject("SystemTrayTexture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        internal static string TaskBar_Height {
            get {
                return ResourceManager.GetString("TaskBar.Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string TaskBar_TextureSource {
            get {
                return ResourceManager.GetString("TaskBar.TextureSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TaskbarTexture {
            get {
                object obj = ResourceManager.GetObject("TaskbarTexture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,3.
        /// </summary>
        internal static string TaskButton_LeftBorderLocation {
            get {
                return ResourceManager.GetString("TaskButton.LeftBorderLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 157,3.
        /// </summary>
        internal static string TaskButton_RightBorderLocation {
            get {
                return ResourceManager.GetString("TaskButton.RightBorderLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3,154.
        /// </summary>
        internal static string TaskButton_TextureLocation {
            get {
                return ResourceManager.GetString("TaskButton.TextureLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string TaskButtonGroupWindow_BorderSize {
            get {
                return ResourceManager.GetString("TaskButtonGroupWindow.BorderSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,3,0,-2.
        /// </summary>
        internal static string TaskButtonGroupWindow_TaskButtonRealSize {
            get {
                return ResourceManager.GetString("TaskButtonGroupWindow.TaskButtonRealSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TaskButtonGroupWindowBorder {
            get {
                object obj = ResourceManager.GetObject("TaskButtonGroupWindowBorder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TaskButtonNormal {
            get {
                object obj = ResourceManager.GetObject("TaskButtonNormal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TaskButtonNormalHover {
            get {
                object obj = ResourceManager.GetObject("TaskButtonNormalHover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TaskButtonPressed {
            get {
                object obj = ResourceManager.GetObject("TaskButtonPressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TaskButtonPressedHover {
            get {
                object obj = ResourceManager.GetObject("TaskButtonPressedHover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
