name: .NET Core Desktop

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    
    env:
      SCTT_PATH: './SimpleClassicTheme.Taskbar/SimpleClassicTheme.Taskbar'
    
    outputs:
      version: ${{ steps.fetch-version.outputs.version }}
      
    steps:
    - name: Check out Common
      uses: actions/checkout@v2
      with:
        path: 'SimpleClassicTheme.Common'
        repository: 'WinClassic/SimpleClassicTheme.Common'

    - name: Check out Taskbar
      uses: actions/checkout@v2
      with:
        path: 'SimpleClassicTheme.Taskbar'

    - name: Restore packages
      run: dotnet restore
      working-directory: ${{ env.SCTT_PATH }}
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Build SCTT x86
      run: 'msbuild -p:Configuration=Release -p:Platform=x86 "${{ env.SCTT_PATH }}.sln"'
      working-directory: ./

    - name: Build SCTT x64
      run: 'msbuild -p:Configuration=Release -p:Platform=x64 "${{ env.SCTT_PATH }}.sln"'
      working-directory: ./

    - name: Upload x86 build artifacts
      uses: actions/upload-artifact@v2.2.3
      with:
        name: SimpleClassicTheme.Taskbar_x86
        path: '${{ env.SCTT_PATH }}/bin/x86/Release/net5.0-windows'

    - name: Upload x64 build artifacts
      uses: actions/upload-artifact@v2.2.3
      with:
        name: SimpleClassicTheme.Taskbar_x64
        path: '${{ env.SCTT_PATH }}/bin/x64/Release/net5.0-windows'
        
    - name: Fetch version string
      id: fetch-version
      run: '${{ env.SCTT_PATH }}/bin/x86/Release/net5.0-windows/SimpleClassicTheme.Taskbar.exe raw-version'
      working-directory: ./

  release:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    needs: [build]
    steps:
    - name: Download x86 build artifacts 
      uses: actions/download-artifact@v2.0.9
      with:
        name: SimpleClassicTheme.Taskbar_x86
        path: SimpleClassicTheme.Taskbar_x86

    - name: Download x64 build artifacts
      uses: actions/download-artifact@v2.0.9
      with:
        name: SimpleClassicTheme.Taskbar_x64
        path: SimpleClassicTheme.Taskbar_x64
        
    - name: Zip files for x86
      run: zip -r SimpleClassicTheme.Taskbar_x86.zip SimpleClassicTheme.Taskbar_x86

    - name: Zip files for x64
      run: zip -r SimpleClassicTheme.Taskbar_x64.zip SimpleClassicTheme.Taskbar_x64

    - name: Publish release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build (${{ needs.build.outputs.version }})"
        files: |
          SimpleClassicTheme.Taskbar_x86.zip
          SimpleClassicTheme.Taskbar_x64.zip
      
  sentry:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    needs: [release]
    steps:
    - name: Check out
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Sentry Release
      uses: getsentry/action-release@v1.1.6
      with:
        environment: "development"
        version: ${{ needs.build.outputs.version }}
        ignore_missing: true
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
        SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
