name: .NET Core Desktop

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Restore packages
      run: dotnet restore
      working-directory: ./SimpleClassicThemeTaskbar/
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Build UnmanagedCode
      run: msbuild -noLogo -p:Configuration=Release
      working-directory: ./SimpleClassicThemeTaskbar.UnmanagedCode/
      
    - name: Build SCTT
      run: msbuild -noLogo -p:Configuration=Release
      working-directory: ./SimpleClassicThemeTaskbar/

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2.2.3
      with:
        name: binaries
        path: './SimpleClassicThemeTaskbar/bin/Release/net5.0-windows'
