name: .NET Core Desktop

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Restore packages
      run: dotnet restore
      working-directory: ./SimpleClassicThemeTaskbar/
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Build SCTT x86
      run: msbuild -p:Configuration=Release -p:Platform=x86 SimpleClassicThemeTaskbar.sln
      working-directory: ./

    - name: Build SCTT x64
      run: msbuild -p:Configuration=Release -p:Platform=AMD64 SimpleClassicThemeTaskbar.sln
      working-directory: ./

    - name: Copy dependencies file for x86
      run: Copy-Item -Path "./build/SimpleClassicThemeTaskbar.deps.json" -Destination "./SimpleClassicThemeTaskbar/bin/x86/Release/net5.0-windows" -Force 
      working-directory: ./

    - name: Copy dependencies file for x64
      run: Copy-Item -Path "./build/SimpleClassicThemeTaskbar.deps.json" -Destination "./SimpleClassicThemeTaskbar/bin/x64/Release/net5.0-windows" -Force 
      working-directory: ./

    - name: Upload x86 build artifacts
      uses: actions/upload-artifact@v2.2.3
      with:
        name: SimpleClassicThemeTaskbar_x86
        path: './SimpleClassicThemeTaskbar/bin/x86/Release/net5.0-windows'

    - name: Upload x64 build artifacts
      uses: actions/upload-artifact@v2.2.3
      with:
        name: SimpleClassicThemeTaskbar_x64
        path: './SimpleClassicThemeTaskbar/bin/x64/Release/net5.0-windows'

  release:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    needs: [build]
    steps:
    - name: Download x86 build artifacts 
      uses: actions/download-artifact@v2.0.9
      with:
        name: SimpleClassicThemeTaskbar_x86
        path: SimpleClassicThemeTaskbar_x86

    - name: Download x64 build artifacts
      uses: actions/download-artifact@v2.0.9
      with:
        name: SimpleClassicThemeTaskbar_x64
        path: SimpleClassicThemeTaskbar_x64
        
    - name: Zip files for x86
      run: zip -r SimpleClassicThemeTaskbar_x86.zip SimpleClassicThemeTaskbar_x86

    - name: Zip files for x64
      run: zip -r SimpleClassicThemeTaskbar_x64.zip SimpleClassicThemeTaskbar_x64
        
    - name: Publish release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          SimpleClassicThemeTaskbar_x86.zip
          SimpleClassicThemeTaskbar_x64.zip
