name: .NET Core Desktop

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Restore packages
      run: dotnet restore
      working-directory: ./SimpleClassicThemeTaskbar/
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Build SCTT x86
      run: msbuild SimpleClassicThemeTaskbar.sln -noLogo -p:Configuration=Release -p:Plaform="x86"
      working-directory: ./

    - name: Build SCTT x64
      run: msbuild SimpleClassicThemeTaskbar.sln -noLogo -p:Configuration=Release -p:Plaform="AMD64"
      working-directory: ./

    - name: Upload x86 build artifacts
      uses: actions/upload-artifact@v2.2.3
      with:
        name: SimpleClassicThemeTaskbar_x86
        path: './SimpleClassicThemeTaskbar/bin/Release/x86/net5.0-windows'

    - name: Upload x64 build artifacts
      uses: actions/upload-artifact@v2.2.3
      with:
        name: SimpleClassicThemeTaskbar_x64
        path: './SimpleClassicThemeTaskbar/bin/Release/x64/net5.0-windows'

  release:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    needs: [build]
    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v2.0.9
      with:
        name: binaries
        path: binaries
        
    - name: Zip files
      run: zip -r binaries.zip binaries
        
    - name: Publish release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: 'binaries.zip'
